# Generated by Django 2.0.5 on 2018-05-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0002_auto_20180529_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default_status', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
