# Generated by Django 2.0.5 on 2018-06-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0007_auto_20180606_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('start', models.IntegerField(default=0)),
                ('end', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['start'],
            },
        ),
    ]
