# Generated by Django 2.0.5 on 2018-06-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('prefix', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
