# Generated by Django 2.0.5 on 2018-06-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0005_auto_20180606_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.ManyToManyField(to='galery.Image'),
        ),
    ]
